### ISSUE TITLE
Codigos de interaccion con la terminal

### ISSUE THREAD

**Issue by Corte0** [ffpp2003/SAPEIClient#41]
Implementar la interaccion cliente terminal a travez del serial.
Para esto implementar clase balanceHandler.

Codigos a implementar:
- OK (saldo descontado)
- Sin saldo suficiente
- Proximo a agotarse (ultima pasada) (saldo descontado)
- Cliente no registrado

(Se deben asignar diferentes codigos de error en Error.h ) (SAPEICore issue)

**Comment by Ignagx** [comment]
Se agregó codigos de terminal "TR_OK" , "TR_ERROR" y "TR_LAST_PASS". Deben ser agregados a Error.h
